### ISSUE TITLE
4 errors on first install and compile.

### ISSUE THREAD

**Issue by PaleLebouf** [Ruhrpottpatriot/OnlineSubsystemEpic#12]
![image](https://user-images.githubusercontent.com/28328592/85351999-fc76d700-b4d2-11ea-9aaa-8fed4584e927.png)

This is dragging and dropping and following all instructions completely. Version 4.24 of UE4.

1. Type conversion from FString to enum through assignment operator is not properly done.
2. Illegal indrection. You're dereferencing a pointer and then trying to use it as a pointer.
3. See 1.
4. FScopeLock has no such member "unlock"

**Comment by Ruhrpottpatriot** [comment]
> Type conversion from FString to enum through assignment operator is not properly done.

The line mentioned in your error doesn't convert from Enum to string. The code is:
```task->Credentials.Type = FUtils::GetEnumValueAsString<ELoginType>("ELoginType", loginType);``` 

With the `GetEnumValueAsString` having the following signature.
```FString GetEnumValueAsString(const FString& Name, TEnum Value)``` 


> Illegal indrection. You're dereferencing a pointer and then trying to use it as a pointer.

The code in the mentioned line is a valid UE_LOG call:
```UE_LOG_ONLINE_IDENTITY(Fatal, TEXT("Login of type %s not supported"), *AccountCredentials.Type);```

So without knowing what your actual code is, I cannot reproduce the compile errors.

**Comment by PaleLebouf** [comment]
There is not extra code with that. This was putting the plugin into a completely blank project. UE did not like it period and refused to compile due to these errors after I cloned and implemented the plugin following the steps outlined in the readme.

**Comment by Ruhrpottpatriot** [comment]
Since it compiles on my end, the code looks correct and I cannot reproduce the error on my end, there's no way for me to "fix" anything.
