### ISSUE TITLE
Session creation always returns EOS_NotFound error

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [Ruhrpottpatriot/OnlineSubsystemEpic#17]
>Session creation does not work because of an EOS_NotFound error.
>Reason is probably: 2 SessionModificationHandles are being created when creating a session. On top of creating 2 SessionModificationHandles the second one, which gets created with "EOS_Sessions_UpdateSessionModification" (which should only be used if the session already exists) throws the EOS_NotFound error. Removing the second one should fix the problem.

Ref #15

**Comment by xuelongmu** [comment]
Also finding this same issue. Specifically, I'm getting the EOS_NotFound error on line 1590 of OnlineSessionInterfaceEpic.cpp:

eosResult = EOS_Sessions_UpdateSessionModification(this->sessionsHandle, &sessionModificationOptions, &modificationHandle);

In addition to the error, the method also nullifies modificationHandle.

Everything before line 1590 - CreateSessionModification, CreateSessionModificationHandle (updating the modificationHandle with custom attributes) doesn't return an error.

Because of this, new sessions cannot be created.

**Comment by xuelongmu** [comment]
I believe @Qyg0n was right in removing the call to `EOS_Sessions_UpdateSessionModification`, which happens after `EOS_Sessions_CreateSessionModification`. UpdateSessionModification is looking for a handle that hasn't been created yet.
When I removed this call, I also saw that there was no else statement for `if (err.IsEmpty())` after calling `CreateSessionModificationHandle`, which is where custom attributes get set. After including this else statement, I found that the first time we call CreateSessionModificationHandle, it errors out when setting a custom attribute. The second time, it works fine and the session is created successfully. I'm not sure why this is the case, will make a separate issue for it.

**Comment by Ruhrpottpatriot** [comment]
Removing the call to `EOS_Sessions_UpdateSessionModification` will not update the session with the attribute that have been passed into the method. In the SDK docs it is stated that the process to create a session is a two step process.

1. Establish the initial state and settings for the session locally with the `EOS_Sessions_CreateSessionModification` function. If the `EOS_Sessions_CreateSessionModification` call succeeds, it will return `EOS_Success` and the default `EOS_HSessionModification` you provided will contain a valid handle. 
2. Modify the session's initial setup all the modifications are made.
3. Complete the process by calling `EOS_Sessions_UpdateSession` with an `EOS_Sessions_UpdateSessionOptions` structure.

I'll talk with some Epic guys on Discord later today and see if I can resolve that issue. This might be an SDK bug.

**Comment by Ruhrpottpatriot** [comment]
See @Qyg0n's PR for a fix. I'm not super happy, as I found some additional bugs, but for now please test this.
