### ISSUE TITLE
"ELoginType" is not a recognized login flow

### ISSUE THREAD

**Issue by fischfroschi** [Ruhrpottpatriot/OnlineSubsystemEpic#27]
The login process again fails as in version 0.2 with the error:
`LogOnlineIdentity: Warning: OSS: FOnlineIdentityInterfaceEpic::Login encountered an error. Message: "ELoginType" is not a recognized login flow.`

**Comment by Ruhrpottpatriot** [comment]
Please use the bug template and provide additional information. With what little you have provided duplicating the issue will be an issue.

**Comment by fischfroschi** [comment]
Heho, this error always happens when I use the login node.  Then "On Fail" is triggered and the above-mentioned message can be found in the output log.  Unfortunately I don't have any more information D:
