### ISSUE TITLE
OnEOSFindSessionComplete causes editor crash

### ISSUE THREAD

**Issue by xuelongmu** [Ruhrpottpatriot/OnlineSubsystemEpic#28]
# Environment
```
Project Version: v0.3
EOS SDK Version: v1.7
Unreal Engine Version: 4.24.3

Other software/plugins that *might* be the cause of the issue?
```

# Steps to reproduce
1. Login via AccountPortal
2. Create a FOnlineSessionSearch object with some simple parameters, these were my settings:
``` 
    bIsLanQuery = false;
    MaxSearchResults = 10;
    PingBucketSize = 1000;
    QuerySettings.Set(FName(TEXT("bUsesStats")), false, EOnlineComparisonOp::Equals);
```
3. Call FindSessions in the OnlineSessionInterfaceEpic:
```
    IOnlineSessionPtr OnlineSession = Online::GetSessionInterface();
    TSharedRef<FOnlineSessionSearch> SearchSettingsRef = SearchSettings.ToSharedRef();
    auto result = OnlineSession->FindSessions(0, SearchSettingsRef);
```
# Expected behaviour
Return a list of sessions that match the search criteria.

# Actual behaviour
When running FindSessions, I can see that the UpdateSessionSearchParameters method is adding the bUsesStats parameter to the EOS_HSessionSearch handle. I checked that there is a valid session using the Epic Dev Portal website's matchmaking dashboard.
The first time I run FindSessions, I get the following error: 
`LogOnline: Error: OSS: [EOS SDK] LogEOSSessions: SearchQuery is empty, search invalid.`
and the OnEOSFindSessionComplete never runs.
The second time I call FindSessions, I don't get that error, then the editor crashes upon reaching this line in OnEOSFindSessionComplete:
`resultCount = EOS_SessionSearch_GetSearchResultCount(*searchHandle, &searchResultCountOptions);
`
with seemingly a nullptr exception:
![image](https://user-images.githubusercontent.com/10490807/86811174-9b5f0f80-c04b-11ea-9ac9-1440dfdc49d9.png)

**Comment by Ruhrpottpatriot** [comment]
Could you post the error log from when the crash happened?

**Comment by Ruhrpottpatriot** [comment]
I tracked the error down to me trying to be clever and using a smart pointer in conjunction with an SDK release function. This issue should be fixed with #15

**Comment by xuelongmu** [comment]
Awesome! I was unable to reproduce the error last night and was going to try again tonight. I'll test out #15 and report back.

**Comment by xuelongmu** [comment]
After creating pull requests for the pr15 branch and the latest commit on the master branch, I'm unfortunately getting a crash on line 153 of `OnlinePrensenceEpic.cpp`:

```LoginId:84b7c7504b10b53179ca5c8b2fe20e06
EpicAccountId:35b2ae6bbcdf43b98f088a3b06dd1d5c

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x002c0016```

I've attached a zip file of the crash here:
[UE4CC-Windows-E5AC20FA4356495DE2705A92B406E357_0001.zip](https://github.com/Ruhrpottpatriot/OnlineSubsystemEpic/files/4899471/UE4CC-Windows-E5AC20FA4356495DE2705A92B406E357_0001.zip)

This crash would happen occasionally before these latest merges, but now it seems to be every time. Perhaps it's related to the smart pointer behavior that was causing the FindSession crash?

**Comment by Ruhrpottpatriot** [comment]
The last one seems a new error related to the presence interface. Can you open a new issue via the "Reference in new issue" option on the top right menu of your post?
