### ISSUE TITLE
CreateSession returns EOS_InvalidParameters on first run

### ISSUE THREAD

**Issue by xuelongmu** [Ruhrpottpatriot/OnlineSubsystemEpic#40]
# Environment
```none
Project Version: 0.0.3
EOS SDK Version: 1.7.0
Unreal Engine Version: 4.24.3

Other software/plugins that *might* be the cause of the issue?
```

# Steps to reproduce
1. Login via AccountPortal
2. Create new session with following settings in FOnlineSessionSettings:
```
    NumPublicConnections = 4;
    NumPrivateConnections=0;
    bAllowJoinInProgress = true;
    bAllowInvites = true;
    bUsesPresence = true;
    bAllowJoinViaPresence = true;
    bAllowJoinViaPresenceFriendsOnly = false;
    bUsesStats = false;
```
and set BucketId from FString input parameter: 
`NewSessionSettings->Set(FName("BucketId"), BucketId, EOnlineDataAdvertisementType::ViaOnlineServiceAndPing);`
3. Call CreateSession with the settings.

# Expected behaviour
Successful creation of new session.

# Actual behaviour
On first run, we get the error 
`[2020.07.17-04.41.49:918][733]LogOnlineSession: Warning: OSS: Cannot update setting: bUsesPresence - Error Code: EOS_InvalidParameters`

The error occurs in the `CreateSessionModificationHandle` method of `OnlineSessionInterfaceEpic`. Specifically, on the following call to the EOS SDK: 
`eosResult = EOS_SessionModification_AddAttribute(ModificationHandle, &attrOpts);`

On a hunch, I also tried to reorder the sequence of adding attributes, so that NumPublicConnections comes first, but with the same result.

On the second run, the session is created successfully.

**Comment by Ruhrpottpatriot** [comment]
Hmm... I can't reproduce the error. And while I found a small bug that the `bShouldAdvertise` parameter is stored as `bUsesPresence` I can successfully create the session. Could you provide a minimal working example and upload it to GoogleDrive/Dropbox/Onedrive/etc. ?

**Comment by xuelongmu** [comment]
[EOSDebugging.zip](https://github.com/Ruhrpottpatriot/OnlineSubsystemEpic/files/4948848/EOSDebugging.zip)

I've uploaded a minimal working example here (without the Config or Plugins folders). The other bugs that I reported can also be found here. In order to use it, open the DefaultMap where there's a BP_MultiplayerTester actor on the level, and Play. The I key will login, O key will logout, N key will create a new session, and F key will find sessions. Let me know if this works, thanks!

**Comment by Ruhrpottpatriot** [comment]
I quickly ran you sample and I can create a session and it also shows on the EOS Dashboard as the following image shows:
![Results](https://user-images.githubusercontent.com/6794359/88081561-10fccc80-cb70-11ea-915f-c606e2be3d89.png)

I have an important meeting tomorrow and I'll look into it in more detail after that.

**Comment by xuelongmu** [comment]
Were you able to find the created session afterwards using the FindSessions method?

**Comment by Ruhrpottpatriot** [comment]
Haven't tested a `FindSession`, but it shows up in the web interface on the first try.

**Comment by xuelongmu** [comment]
I was also able to see it in the web interface without issue, but had no luck retrieving it with FindSessions.

**Comment by Ruhrpottpatriot** [comment]
I'll look into `FindSessions` tomorrow.

**Comment by Ruhrpottpatriot** [comment]
So I cannot reproduce the session creation bug. With your minimal working example everything works as expected. I can also not confirm #41, at least not like you wrote the bug report, I can however confirm another bug regarding to finding sessions.
